create type permission as enum (
	'editor',
	'reader'
);

create table users (
	user_id integer primary key generated by default as identity,
	login text not null,
	password text not null,
	rights permission not null
);

create table seller (
	seller_id integer primary key generated by default as identity,
	user_id integer references users (user_id),
	surname text not null,
	name text not null,
	patronymic text,
	phone_number text not null,
	email text,
	post text -- должность
);

create table buyer (
	buyer_id integer primary key generated by default as identity,
	user_id integer references users (user_id),
	surname text not null,
	name text not null,
	phone_number text not null,
	email text,
	city text,
	street text,
	building text,
	flat smallint
);

create type Category as enum (
	'CPU',
	'GPU',
	'Motherboard',
	'RAM',
	'SSD',
	'HDD',
	'Power supply',
	'Computer case',
	'CPU cooler'
);

create table good (
	good_id integer primary key generated by default as identity, -- он же атрибут/артикул
	name text not null,
	description text,
	specifications text,
	Category Category,
	price float,
	amount smallint
);

create type Delivery as enum (
	'Pickup',
	'ByCourier'
);

create table orders (
	order_id integer primary key generated by default as identity,
	buyer_id integer references buyer (buyer_id),
	delivery_method Delivery -- (самовывоз/курьером)
);

create table buffer (
	buffer_id integer primary key generated by default as identity,
	order_id integer references orders (order_id),
	good_id integer references good (good_id),
	amount smallint
);
